// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/common.proto

package rocketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED        OrderStatus = 0
	OrderStatus_ORDER_STATUS_CREATED            OrderStatus = 1
	OrderStatus_ORDER_STATUS_INVENTORY_RESERVED OrderStatus = 2
	OrderStatus_ORDER_STATUS_INVENTORY_FAILED   OrderStatus = 3
	OrderStatus_ORDER_STATUS_PAYMENT_PENDING    OrderStatus = 4
	OrderStatus_ORDER_STATUS_PAID               OrderStatus = 5
	OrderStatus_ORDER_STATUS_PRODUCTION_STARTED OrderStatus = 6
	OrderStatus_ORDER_STATUS_COMPLETED          OrderStatus = 7
	OrderStatus_ORDER_STATUS_FAILED             OrderStatus = 8
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_CREATED",
		2: "ORDER_STATUS_INVENTORY_RESERVED",
		3: "ORDER_STATUS_INVENTORY_FAILED",
		4: "ORDER_STATUS_PAYMENT_PENDING",
		5: "ORDER_STATUS_PAID",
		6: "ORDER_STATUS_PRODUCTION_STARTED",
		7: "ORDER_STATUS_COMPLETED",
		8: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":        0,
		"ORDER_STATUS_CREATED":            1,
		"ORDER_STATUS_INVENTORY_RESERVED": 2,
		"ORDER_STATUS_INVENTORY_FAILED":   3,
		"ORDER_STATUS_PAYMENT_PENDING":    4,
		"ORDER_STATUS_PAID":               5,
		"ORDER_STATUS_PRODUCTION_STARTED": 6,
		"ORDER_STATUS_COMPLETED":          7,
		"ORDER_STATUS_FAILED":             8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_RESERVED    ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_FAILED      ReservationStatus = 2
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "RESERVATION_STATUS_RESERVED",
		2: "RESERVATION_STATUS_FAILED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"RESERVATION_STATUS_RESERVED":    1,
		"RESERVATION_STATUS_FAILED":      2,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_SUCCEEDED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCEEDED",
		3: "PAYMENT_STATUS_FAILED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_SUCCEEDED":   2,
		"PAYMENT_STATUS_FAILED":      3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[2].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[2]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

type ProductionStatus int32

const (
	ProductionStatus_PRODUCTION_STATUS_UNSPECIFIED ProductionStatus = 0
	ProductionStatus_PRODUCTION_STATUS_STARTED     ProductionStatus = 1
	ProductionStatus_PRODUCTION_STATUS_COMPLETED   ProductionStatus = 2
	ProductionStatus_PRODUCTION_STATUS_FAILED      ProductionStatus = 3
)

// Enum value maps for ProductionStatus.
var (
	ProductionStatus_name = map[int32]string{
		0: "PRODUCTION_STATUS_UNSPECIFIED",
		1: "PRODUCTION_STATUS_STARTED",
		2: "PRODUCTION_STATUS_COMPLETED",
		3: "PRODUCTION_STATUS_FAILED",
	}
	ProductionStatus_value = map[string]int32{
		"PRODUCTION_STATUS_UNSPECIFIED": 0,
		"PRODUCTION_STATUS_STARTED":     1,
		"PRODUCTION_STATUS_COMPLETED":   2,
		"PRODUCTION_STATUS_FAILED":      3,
	}
)

func (x ProductionStatus) Enum() *ProductionStatus {
	p := new(ProductionStatus)
	*p = x
	return p
}

func (x ProductionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[3].Descriptor()
}

func (ProductionStatus) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[3]
}

func (x ProductionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductionStatus.Descriptor instead.
func (ProductionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

type DomainEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainEvent) Reset() {
	*x = DomainEvent{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEvent) ProtoMessage() {}

func (x *DomainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEvent.ProtoReflect.Descriptor instead.
func (*DomainEvent) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *DomainEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DomainEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DomainEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DomainEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DomainEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DomainEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x11rocket.factory.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\tOrderItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\tR\tunitPrice\"\xe9\x01\n" +
	"\vDomainEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\apayload\x18\x06 \x01(\v2\x17.google.protobuf.StructR\apayload*\xa0\x02\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_CREATED\x10\x01\x12#\n" +
	"\x1fORDER_STATUS_INVENTORY_RESERVED\x10\x02\x12!\n" +
	"\x1dORDER_STATUS_INVENTORY_FAILED\x10\x03\x12 \n" +
	"\x1cORDER_STATUS_PAYMENT_PENDING\x10\x04\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x05\x12#\n" +
	"\x1fORDER_STATUS_PRODUCTION_STARTED\x10\x06\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\a\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\b*w\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRESERVATION_STATUS_RESERVED\x10\x01\x12\x1d\n" +
	"\x19RESERVATION_STATUS_FAILED\x10\x02*\x84\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_SUCCEEDED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03*\x93\x01\n" +
	"\x10ProductionStatus\x12!\n" +
	"\x1dPRODUCTION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PRODUCTION_STATUS_STARTED\x10\x01\x12\x1f\n" +
	"\x1bPRODUCTION_STATUS_COMPLETED\x10\x02\x12\x1c\n" +
	"\x18PRODUCTION_STATUS_FAILED\x10\x03B@Z>github.com/petrov-kirill-241-321/rocket-factory/proto;rocketpbb\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_common_proto_goTypes = []any{
	(OrderStatus)(0),              // 0: rocket.factory.v1.OrderStatus
	(ReservationStatus)(0),        // 1: rocket.factory.v1.ReservationStatus
	(PaymentStatus)(0),            // 2: rocket.factory.v1.PaymentStatus
	(ProductionStatus)(0),         // 3: rocket.factory.v1.ProductionStatus
	(*OrderItem)(nil),             // 4: rocket.factory.v1.OrderItem
	(*DomainEvent)(nil),           // 5: rocket.factory.v1.DomainEvent
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
}
var file_proto_common_proto_depIdxs = []int32{
	6, // 0: rocket.factory.v1.DomainEvent.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: rocket.factory.v1.DomainEvent.payload:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
