// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory.proto

package rocketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAvailabilityRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Available     bool                     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Items         []*InventoryAvailability `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Reason        string                   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckAvailabilityResponse) GetItems() []*InventoryAvailability {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckAvailabilityResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InventoryAvailability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Requested     int32                  `protobuf:"varint,2,opt,name=requested,proto3" json:"requested,omitempty"`
	Available     int32                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Enough        bool                   `protobuf:"varint,4,opt,name=enough,proto3" json:"enough,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryAvailability) Reset() {
	*x = InventoryAvailability{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryAvailability) ProtoMessage() {}

func (x *InventoryAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryAvailability.ProtoReflect.Descriptor instead.
func (*InventoryAvailability) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryAvailability) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryAvailability) GetRequested() int32 {
	if x != nil {
		return x.Requested
	}
	return 0
}

func (x *InventoryAvailability) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *InventoryAvailability) GetEnough() bool {
	if x != nil {
		return x.Enough
	}
	return false
}

type ReserveItemsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items          []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveItemsRequest) Reset() {
	*x = ReserveItemsRequest{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsRequest) ProtoMessage() {}

func (x *ReserveItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveItemsRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveItemsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReserveItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=rocket.factory.v1.ReservationStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsResponse) Reset() {
	*x = ReserveItemsResponse{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsResponse) ProtoMessage() {}

func (x *ReserveItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsResponse.ProtoReflect.Descriptor instead.
func (*ReserveItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveItemsResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveItemsResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *ReserveItemsResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\x11rocket.factory.v1\x1a\x12proto/common.proto\"N\n" +
	"\x18CheckAvailabilityRequest\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.rocket.factory.v1.OrderItemR\x05items\"\x91\x01\n" +
	"\x19CheckAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12>\n" +
	"\x05items\x18\x02 \x03(\v2(.rocket.factory.v1.InventoryAvailabilityR\x05items\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"}\n" +
	"\x15InventoryAvailability\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1c\n" +
	"\trequested\x18\x02 \x01(\x05R\trequested\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x05R\tavailable\x12\x16\n" +
	"\x06enough\x18\x04 \x01(\bR\x06enough\"\xa6\x01\n" +
	"\x13ReserveItemsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\x05items\x18\x03 \x03(\v2\x1c.rocket.factory.v1.OrderItemR\x05items\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\x93\x01\n" +
	"\x14ReserveItemsResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.rocket.factory.v1.ReservationStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xe3\x01\n" +
	"\x10InventoryService\x12n\n" +
	"\x11CheckAvailability\x12+.rocket.factory.v1.CheckAvailabilityRequest\x1a,.rocket.factory.v1.CheckAvailabilityResponse\x12_\n" +
	"\fReserveItems\x12&.rocket.factory.v1.ReserveItemsRequest\x1a'.rocket.factory.v1.ReserveItemsResponseB@Z>github.com/petrov-kirill-241-321/rocket-factory/proto;rocketpbb\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_inventory_proto_goTypes = []any{
	(*CheckAvailabilityRequest)(nil),  // 0: rocket.factory.v1.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil), // 1: rocket.factory.v1.CheckAvailabilityResponse
	(*InventoryAvailability)(nil),     // 2: rocket.factory.v1.InventoryAvailability
	(*ReserveItemsRequest)(nil),       // 3: rocket.factory.v1.ReserveItemsRequest
	(*ReserveItemsResponse)(nil),      // 4: rocket.factory.v1.ReserveItemsResponse
	(*OrderItem)(nil),                 // 5: rocket.factory.v1.OrderItem
	(ReservationStatus)(0),            // 6: rocket.factory.v1.ReservationStatus
}
var file_proto_inventory_proto_depIdxs = []int32{
	5, // 0: rocket.factory.v1.CheckAvailabilityRequest.items:type_name -> rocket.factory.v1.OrderItem
	2, // 1: rocket.factory.v1.CheckAvailabilityResponse.items:type_name -> rocket.factory.v1.InventoryAvailability
	5, // 2: rocket.factory.v1.ReserveItemsRequest.items:type_name -> rocket.factory.v1.OrderItem
	6, // 3: rocket.factory.v1.ReserveItemsResponse.status:type_name -> rocket.factory.v1.ReservationStatus
	0, // 4: rocket.factory.v1.InventoryService.CheckAvailability:input_type -> rocket.factory.v1.CheckAvailabilityRequest
	3, // 5: rocket.factory.v1.InventoryService.ReserveItems:input_type -> rocket.factory.v1.ReserveItemsRequest
	1, // 6: rocket.factory.v1.InventoryService.CheckAvailability:output_type -> rocket.factory.v1.CheckAvailabilityResponse
	4, // 7: rocket.factory.v1.InventoryService.ReserveItems:output_type -> rocket.factory.v1.ReserveItemsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
