// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/production.proto

package rocketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductionTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductionTaskRequest) Reset() {
	*x = GetProductionTaskRequest{}
	mi := &file_proto_production_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductionTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductionTaskRequest) ProtoMessage() {}

func (x *GetProductionTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_production_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductionTaskRequest.ProtoReflect.Descriptor instead.
func (*GetProductionTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_production_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductionTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ProductionTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        ProductionStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=rocket.factory.v1.ProductionStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionTask) Reset() {
	*x = ProductionTask{}
	mi := &file_proto_production_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionTask) ProtoMessage() {}

func (x *ProductionTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_production_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionTask.ProtoReflect.Descriptor instead.
func (*ProductionTask) Descriptor() ([]byte, []int) {
	return file_proto_production_proto_rawDescGZIP(), []int{1}
}

func (x *ProductionTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductionTask) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProductionTask) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProductionTask) GetStatus() ProductionStatus {
	if x != nil {
		return x.Status
	}
	return ProductionStatus_PRODUCTION_STATUS_UNSPECIFIED
}

func (x *ProductionTask) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProductionTask) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ProductionTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductionTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_production_proto protoreflect.FileDescriptor

const file_proto_production_proto_rawDesc = "" +
	"\n" +
	"\x16proto/production.proto\x12\x11rocket.factory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12proto/common.proto\"3\n" +
	"\x18GetProductionTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x81\x03\n" +
	"\x0eProductionTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.rocket.factory.v1.ProductionStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2x\n" +
	"\x11ProductionService\x12c\n" +
	"\x11GetProductionTask\x12+.rocket.factory.v1.GetProductionTaskRequest\x1a!.rocket.factory.v1.ProductionTaskB@Z>github.com/petrov-kirill-241-321/rocket-factory/proto;rocketpbb\x06proto3"

var (
	file_proto_production_proto_rawDescOnce sync.Once
	file_proto_production_proto_rawDescData []byte
)

func file_proto_production_proto_rawDescGZIP() []byte {
	file_proto_production_proto_rawDescOnce.Do(func() {
		file_proto_production_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_production_proto_rawDesc), len(file_proto_production_proto_rawDesc)))
	})
	return file_proto_production_proto_rawDescData
}

var file_proto_production_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_production_proto_goTypes = []any{
	(*GetProductionTaskRequest)(nil), // 0: rocket.factory.v1.GetProductionTaskRequest
	(*ProductionTask)(nil),           // 1: rocket.factory.v1.ProductionTask
	(ProductionStatus)(0),            // 2: rocket.factory.v1.ProductionStatus
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
}
var file_proto_production_proto_depIdxs = []int32{
	2, // 0: rocket.factory.v1.ProductionTask.status:type_name -> rocket.factory.v1.ProductionStatus
	3, // 1: rocket.factory.v1.ProductionTask.started_at:type_name -> google.protobuf.Timestamp
	3, // 2: rocket.factory.v1.ProductionTask.completed_at:type_name -> google.protobuf.Timestamp
	3, // 3: rocket.factory.v1.ProductionTask.created_at:type_name -> google.protobuf.Timestamp
	3, // 4: rocket.factory.v1.ProductionTask.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: rocket.factory.v1.ProductionService.GetProductionTask:input_type -> rocket.factory.v1.GetProductionTaskRequest
	1, // 6: rocket.factory.v1.ProductionService.GetProductionTask:output_type -> rocket.factory.v1.ProductionTask
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_production_proto_init() }
func file_proto_production_proto_init() {
	if File_proto_production_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_production_proto_rawDesc), len(file_proto_production_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_production_proto_goTypes,
		DependencyIndexes: file_proto_production_proto_depIdxs,
		MessageInfos:      file_proto_production_proto_msgTypes,
	}.Build()
	File_proto_production_proto = out.File
	file_proto_production_proto_goTypes = nil
	file_proto_production_proto_depIdxs = nil
}
